### PR TITLE
adds utf-8 encoding to files to conform to pep-0263

### PR DESCRIPTION
**Pull request by tasdikrahman**
Saw that the files inside packages don't have the encoding mentioned. Added them in this PR

### CODE REVIEW

**Comment by sils** [comment]
can you squash your commits?

**Comment by sils** [comment]
sorry for being so unresponsive to your PRs, you can btw. talk to us at https://gitter.im/coala-analyzer/coala - especially if you need any kind of help there's plenty of people around.

**Comment by sils** [comment]
can you take a look at http://coala.readthedocs.org/en/latest/Getting_Involved/Writing_Good_Commits.html

**Comment by sils** [comment]
ok now please squash your commits again and make one good message from it. Look at the example, use `Remove` not `removed` (casing and tense!) and so on

**Comment by sils** [comment]
way better, can we remove the `Pyprint:` because people know very well on their own at what repository they're looking. Secondly use `Add`, not `Added` - do not use the past tense! Not "I have done that" but "Do that" that's the commit message style.

**Comment by tasdikrahman** [comment]
@sils1297 Done. :+1: Removed `Pyprint` and changed `Added` -> `Add`

**Comment by sils** [comment]
ack 3d6c6d1 - awesome :)

**Comment by SanketDG** [comment]
@rultor merge

**Pull request merged**
